### ISSUE TITLE
Problem extracting items

### ISSUE THREAD

**Issue by cristianqx** [kaiserdj/rl-garage-assets#6]
Hello good afternoon!
Congratulations on the work, a year ago your project helped me a lot, but I needed to use it again and it is no longer capturing the images from the website, the url it is bringing in the output json is incorrect.

I've already searched the entire web and haven't found a project as good as yours.

I would like to know if you will update it to fix these bugs so that it works again.

Thanks

**Comment by kaiserdj** [comment]
It's working again since the commit [53e6c0e
](https://github.com/kaiserdj/rl-garage-assets/commit/53e6c0ea921494626cb3826a572ed3a548f676d2)
